services:
    db:
        image: postgres:16-alpine
        environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=password
        ports:
            - '5432:5432'
        volumes:
            - postgres13:/var/lib/postgresql/data
    redis:
        image: redis:7.0.15-alpine
        ports:
        - '6379:6379'
    web:
        build: .
        command: bash -c "bundle install && rm -f tmp/pids/server.pid && bundle exec rails db:migrate && bundle exec rails s -b '0.0.0.0'"
        environment:
            - RAILS_MAX_THREADS=5
            - MYAPP_DATABASE_PASSWORD=supersecret
            - REDIS_URL=redis://redis:6379/0
        volumes:
        - .:/myapp
        ports:
        - "3000:3000"
        depends_on:
        - db
        - redis
    
    sidekiq:
        build: .
        command: bundle exec sidekiq
        environment:
            - REDIS_URL=redis://redis:6379/0
        volumes:
            - .:/myapp
        depends_on:
            - db
            - redis
    # test:
    #     build: .
    #     command: bundle exec rspec
    #     volumes:
    #         - .:/rails
    #     depends_on:
    #         - db
    #         - redis 
    #     environment:
    #         - DATABASE_URL: postgresql://postgres:password@db:5432/myapp_test
    #         - REDIS_URL: redis://redis:6379/0
volumes:
    postgres13: